import Foundation
import UniformTypeIdentifiers

nonisolated enum ClipboardContentKind: String, Codable, Sendable {
    case text
    case url
    case file
    case image
    case mixed
    case data
}

nonisolated enum ClipboardContentFilter: String, CaseIterable, Sendable {
    case all
    case text
    case image
    case url
    case file
}

nonisolated enum ClipboardKnownMarker: String, CaseIterable, Codable, Sendable {
    case concealed = "org.nspasteboard.ConcealedType"
    case transient = "org.nspasteboard.TransientType"
    case autoGenerated = "org.nspasteboard.AutoGeneratedType"
    case source = "org.nspasteboard.source"
    case remoteClipboard = "com.apple.is-remote-clipboard"

    var shouldMaskByDefault: Bool {
        switch self {
        case .concealed, .transient, .autoGenerated:
            true
        case .source, .remoteClipboard:
            false
        }
    }
}

nonisolated struct ClipboardApplicationSource: Codable, Equatable, Sendable {
    var name: String?
    var bundleIdentifier: String?
    var bundlePath: String?
    var rawValue: String?

    var displayName: String? {
        name ?? bundleIdentifier ?? rawValue
    }
}

nonisolated enum ClipboardPasteboardAccessBehavior: String, Codable, Sendable {
    case systemDefault
    case ask
    case alwaysAllow
    case alwaysDeny
    case unknown
}

nonisolated enum ClipboardHistoryAccessIssue: Equatable, Sendable {
    case readDenied(ClipboardPasteboardAccessBehavior)
    case readFailed(String)
    case pasteCommandDenied
}

nonisolated struct ClipboardHistoryRecordNotice: Equatable, Identifiable, Sendable {
    var id: UUID
    var entryID: UUID
    var changeCount: Int
    var kind: ClipboardContentKind

    init(id: UUID = UUID(), entry: ClipboardHistoryEntry) {
        self.id = id
        self.entryID = entry.id
        self.changeCount = entry.changeCount
        self.kind = entry.kind
    }
}

nonisolated struct ClipboardStoredRepresentation: Codable, Equatable, Sendable {
    var type: String
    var blobID: String
    var byteCount: Int
}

nonisolated struct ClipboardHistoryItem: Codable, Equatable, Identifiable, Sendable {
    var id: UUID
    var kind: ClipboardContentKind
    var displayText: String
    var searchableText: String
    var markerTypes: [String]
    var representations: [ClipboardStoredRepresentation]
    var imageBlobID: String?
    var imagePixelWidth: Double?
    var imagePixelHeight: Double?

    var shouldMaskByDefault: Bool {
        markerTypes.contains(where: ClipboardMarkerClassifier.shouldMaskByDefault)
    }

    var blobIDs: [String] {
        var ids = representations.map(\.blobID)
        if let imageBlobID, !ids.contains(imageBlobID) {
            ids.append(imageBlobID)
        }
        return ids
    }
}

nonisolated struct ClipboardHistoryEntry: Codable, Equatable, Identifiable, Sendable {
    var id: UUID
    var changeCount: Int
    var createdAt: Date
    var kind: ClipboardContentKind
    var displayText: String
    var searchableText: String
    var markerTypes: [String]
    var declaredSource: ClipboardApplicationSource?
    var inferredSource: ClipboardApplicationSource?
    var items: [ClipboardHistoryItem]
    var fingerprint: String

    var shouldMaskByDefault: Bool {
        markerTypes.contains(where: ClipboardMarkerClassifier.shouldMaskByDefault)
            || items.contains(where: \.shouldMaskByDefault)
    }

    var primarySource: ClipboardApplicationSource? {
        declaredSource ?? inferredSource
    }

    var blobIDs: [String] {
        Array(Set(items.flatMap(\.blobIDs))).sorted()
    }

    func matches(searchText query: String) -> Bool {
        let normalizedQuery = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalizedQuery.isEmpty else {
            return true
        }

        return searchableText.localizedCaseInsensitiveContains(normalizedQuery)
            || displayText.localizedCaseInsensitiveContains(normalizedQuery)
            || markerTypes.joined(separator: " ").localizedCaseInsensitiveContains(normalizedQuery)
            || (primarySource?.displayName?.localizedCaseInsensitiveContains(normalizedQuery) ?? false)
    }

    func matches(contentFilter filter: ClipboardContentFilter) -> Bool {
        switch filter {
        case .all:
            true
        case .text:
            contains(kind: .text)
        case .image:
            contains(kind: .image)
        case .url:
            contains(kind: .url)
        case .file:
            contains(kind: .file)
        }
    }

    private func contains(kind targetKind: ClipboardContentKind) -> Bool {
        kind == targetKind || items.contains { $0.kind == targetKind }
    }
}

nonisolated struct ClipboardCapturedRepresentation: Equatable, Sendable {
    var type: String
    var data: Data
}

nonisolated struct ClipboardCapturedItem: Equatable, Sendable {
    var markerTypes: [String]
    var representations: [ClipboardCapturedRepresentation]
}

nonisolated struct ClipboardPasteboardSnapshot: Equatable, Sendable {
    var changeCount: Int
    var capturedAt: Date
    var declaredSource: ClipboardApplicationSource?
    var inferredSource: ClipboardApplicationSource?
    var items: [ClipboardCapturedItem]
}

nonisolated struct ClipboardHistoryBuildResult: Sendable {
    var entry: ClipboardHistoryEntry
    var blobs: [String: Data]
}

nonisolated enum ClipboardMarkerClassifier {
    static let knownTypes = Set(ClipboardKnownMarker.allCases.map(\.rawValue))
    static let legacyTransientTypes: Set<String> = [
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    static func markers(in types: some Sequence<String>) -> [String] {
        let markers = types.filter(isMarker)
        return Array(Set(markers)).sorted()
    }

    static func isMarker(_ type: String) -> Bool {
        knownTypes.contains(type)
            || legacyTransientTypes.contains(type)
            || inferredMarkerType(type)
    }

    static func shouldMaskByDefault(_ type: String) -> Bool {
        if let marker = ClipboardKnownMarker(rawValue: type) {
            return marker.shouldMaskByDefault
        }

        let normalizedType = type.lowercased()
        return legacyTransientTypes.contains(type)
            || normalizedType.contains("concealed")
            || normalizedType.contains("transient")
            || normalizedType.contains("autogenerated")
            || normalizedType.contains("auto-generated")
    }

    private static func inferredMarkerType(_ type: String) -> Bool {
        let normalizedType = type.lowercased()
        return normalizedType.contains("concealed")
            || normalizedType.contains("transient")
            || normalizedType.contains("autogenerated")
            || normalizedType.contains("auto-generated")
            || isRemoteClipboard(type)
    }

    static func isRemoteClipboard(_ type: String) -> Bool {
        if ClipboardKnownMarker(rawValue: type) == .remoteClipboard {
            return true
        }

        let normalizedType = type.lowercased()
        return normalizedType.contains("remote") && normalizedType.contains("clipboard")
    }
}

nonisolated enum ClipboardPasteboardTypeClassifier {
    static let plainTextTypes: Set<String> = [
        "public.utf8-plain-text",
        "public.utf16-plain-text",
        "public.plain-text",
        "NSStringPboardType",
        "public.text",
    ]

    static let urlTypes: Set<String> = [
        "public.url",
        "NSURLPboardType",
    ]

    static let fileURLTypes: Set<String> = [
        "public.file-url",
        "NSFilenamesPboardType",
    ]

    static let htmlTypes: Set<String> = [
        "public.html",
        "text/html",
        "Apple HTML pasteboard type",
    ]

    static let richTextTypes: Set<String> = [
        "public.rtf",
        "public.rtfd",
        "NSRTFPboardType",
        "NeXT Rich Text Format v1.0 pasteboard type",
    ]

    static let imageTypes: Set<String> = [
        "public.png",
        "public.tiff",
        "public.jpeg",
        "public.heic",
        "public.image",
        "Apple PNG pasteboard type",
        "NeXT TIFF v4.0 pasteboard type",
    ]

    static func isText(_ type: String) -> Bool {
        plainTextTypes.contains(type)
    }

    static func isURL(_ type: String) -> Bool {
        urlTypes.contains(type)
    }

    static func isFileURL(_ type: String) -> Bool {
        fileURLTypes.contains(type)
    }

    static func isHTML(_ type: String) -> Bool {
        htmlTypes.contains(type)
    }

    static func isRichText(_ type: String) -> Bool {
        richTextTypes.contains(type)
    }

    static func isImage(_ type: String) -> Bool {
        imageTypes.contains(type)
    }

    static func isImageFilePath(_ path: String) -> Bool {
        let fileExtension = URL(fileURLWithPath: path).pathExtension
        guard
            !fileExtension.isEmpty,
            let type = UTType(filenameExtension: fileExtension)
        else {
            return false
        }

        return type.conforms(to: .image)
    }

    static func imageType(forFilePath path: String) -> String {
        let fileExtension = URL(fileURLWithPath: path).pathExtension
        guard
            !fileExtension.isEmpty,
            let type = UTType(filenameExtension: fileExtension),
            type.conforms(to: .image)
        else {
            return "public.png"
        }

        return type.identifier
    }
}
