import Foundation
import XCTest
@testable import pulse

@MainActor
final class ClipboardHistoryStoreTests: XCTestCase {
    func testMarkerBackedSensitiveItemsAreStoredSearchableAndCopyable() throws {
        let client = FakeClipboardPasteboardClient()
        let store = makeStore(client: client)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 1,
            capturedAt: Date(),
            declaredSource: ClipboardApplicationSource(
                name: "Password App",
                bundleIdentifier: "com.example.passwords",
                bundlePath: nil,
                rawValue: "com.example.passwords"
            ),
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [ClipboardKnownMarker.concealed.rawValue],
                    representations: [
                        ClipboardCapturedRepresentation(
                            type: ClipboardKnownMarker.concealed.rawValue,
                            data: Data()
                        ),
                        ClipboardCapturedRepresentation(
                            type: "public.utf8-plain-text",
                            data: Data("123456".utf8)
                        ),
                    ]
                ),
            ]
        )

        store.record(snapshot)

        XCTAssertEqual(store.entries.count, 1)
        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertTrue(entry.shouldMaskByDefault)
        XCTAssertTrue(entry.markerTypes.contains(ClipboardKnownMarker.concealed.rawValue))
        XCTAssertTrue(entry.matches(searchText: "123456"))

        store.copy(entry)

        XCTAssertTrue(client.writtenRepresentations.map(\.type).contains(ClipboardKnownMarker.concealed.rawValue))
        XCTAssertTrue(client.writtenRepresentations.contains { representation in
            representation.type == "public.utf8-plain-text"
                && String(data: representation.data, encoding: .utf8) == "123456"
        })
    }

    func testMarkerLabelsOnlyExposeRemoteClipboardState() throws {
        let store = makeStore()
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 1,
            capturedAt: Date(),
            declaredSource: nil,
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [
                        ClipboardKnownMarker.concealed.rawValue,
                        ClipboardKnownMarker.transient.rawValue,
                        ClipboardKnownMarker.autoGenerated.rawValue,
                        ClipboardKnownMarker.source.rawValue,
                        ClipboardKnownMarker.remoteClipboard.rawValue,
                        "com.example.remote.clipboard",
                    ],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.utf8-plain-text", data: Data("hello".utf8)),
                    ]
                ),
            ]
        ))

        let entry = try XCTUnwrap(store.entries.first)

        XCTAssertEqual(
            store.markerLabels(for: entry, strings: PulseStrings(language: .chinese)),
            ["跨设备"]
        )
        XCTAssertEqual(
            store.markerLabels(for: entry, strings: PulseStrings(language: .english)),
            ["Remote"]
        )
    }

    func testRetentionLimitPrunesEntriesAndDeletesBlobs() {
        let store = makeStore()
        store.retentionLimit = 1

        store.record(textSnapshot(changeCount: 1, text: "first"))
        let prunedBlobIDs = store.entries.flatMap(\.blobIDs)

        store.record(textSnapshot(changeCount: 2, text: "second"))

        XCTAssertEqual(store.entries.count, 1)
        XCTAssertEqual(store.entries.first?.displayText, "second")
        for blobID in prunedBlobIDs {
            XCTAssertNil(store.imageData(for: blobID))
        }
    }

    func testUnlimitedRetentionLimitDoesNotPruneByCount() {
        let store = makeStore()
        store.retentionLimit = ClipboardHistoryStore.unlimitedRetentionLimit

        store.record(textSnapshot(changeCount: 1, text: "first"))
        store.record(textSnapshot(changeCount: 2, text: "second"))
        store.record(textSnapshot(changeCount: 3, text: "third"))

        XCTAssertEqual(store.entries.map(\.displayText), ["third", "second", "first"])
    }

    func testUnlimitedRetentionDaysDoesNotPruneByAge() {
        let store = makeStore()
        store.retentionDays = ClipboardHistoryStore.unlimitedRetentionDays

        store.record(textSnapshot(
            changeCount: 1,
            text: "old",
            capturedAt: Date().addingTimeInterval(-100 * 24 * 60 * 60)
        ))
        store.record(textSnapshot(changeCount: 2, text: "new"))

        XCTAssertEqual(store.entries.map(\.displayText), ["new", "old"])
    }

    func testRecordingPublishesLatestRecordNotice() throws {
        let store = makeStore()

        store.record(textSnapshot(changeCount: 1, text: "first"))

        let entry = try XCTUnwrap(store.entries.first)
        let notice = try XCTUnwrap(store.latestRecordNotice)
        XCTAssertEqual(notice.entryID, entry.id)
        XCTAssertEqual(notice.changeCount, 1)
        XCTAssertEqual(notice.kind, .text)
    }

    func testDuplicateRecordPublishesNewNoticeForRefreshedEntry() throws {
        let store = makeStore()
        store.record(textSnapshot(changeCount: 1, text: "first"))
        let firstNoticeID = try XCTUnwrap(store.latestRecordNotice?.id)
        let entryID = try XCTUnwrap(store.entries.first?.id)

        store.record(textSnapshot(changeCount: 2, text: "first"))

        let notice = try XCTUnwrap(store.latestRecordNotice)
        XCTAssertNotEqual(notice.id, firstNoticeID)
        XCTAssertEqual(notice.entryID, entryID)
        XCTAssertEqual(notice.changeCount, 2)
    }

    func testIgnoredOwnClipboardWriteDoesNotPublishRecordNotice() throws {
        let client = FakeClipboardPasteboardClient()
        let store = makeStore(client: client)
        store.record(textSnapshot(changeCount: 1, text: "first"))
        let firstNotice = store.latestRecordNotice
        let entry = try XCTUnwrap(store.entries.first)

        XCTAssertTrue(store.copy(entry))
        store.record(textSnapshot(changeCount: client.changeCount, text: "first"))

        XCTAssertEqual(store.latestRecordNotice, firstNotice)
    }

    func testClearHistoryDeletesMetadataAndBlobData() {
        let store = makeStore()
        store.record(textSnapshot(changeCount: 1, text: "temporary"))
        let blobIDs = store.entries.flatMap(\.blobIDs)

        store.clearHistory()

        XCTAssertTrue(store.entries.isEmpty)
        XCTAssertNil(store.latestRecordNotice)
        for blobID in blobIDs {
            XCTAssertNil(store.imageData(for: blobID))
        }
    }

    func testRecordsTextURLFileAndImageItems() throws {
        let store = makeStore()
        let fileURL = URL(fileURLWithPath: "/tmp/pulse-report.pdf")
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 3,
            capturedAt: Date(),
            declaredSource: nil,
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.utf8-plain-text", data: Data("plain text".utf8)),
                    ]
                ),
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.url", data: Data("https://example.com".utf8)),
                    ]
                ),
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.file-url", data: Data(fileURL.absoluteString.utf8)),
                    ]
                ),
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.png", data: Data([0x89, 0x50, 0x4E, 0x47])),
                    ]
                ),
            ]
        ))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .mixed)
        XCTAssertEqual(entry.items.map(\.kind), [.text, .url, .file, .image])
        XCTAssertTrue(entry.matches(searchText: "example.com"))
        XCTAssertTrue(entry.matches(searchText: "pulse-report.pdf"))
        XCTAssertNotNil(entry.items.first(where: { $0.kind == .image })?.imageBlobID)
    }

    func testRemoteImageFileURLIsClassifiedAsImage() throws {
        let store = makeStore()
        let imageFileURL = URL(fileURLWithPath: "/Users/example/Library/Group Containers/group.com.apple.coreservices.useractivityd/remote-image.png")
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 4,
            capturedAt: Date(),
            declaredSource: ClipboardApplicationSource(
                name: "Universal Control",
                bundleIdentifier: "com.apple.universalcontrol",
                bundlePath: nil,
                rawValue: nil
            ),
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [ClipboardKnownMarker.remoteClipboard.rawValue],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.file-url", data: Data(imageFileURL.absoluteString.utf8)),
                        ClipboardCapturedRepresentation(type: "public.png", data: Data([0x89, 0x50, 0x4E, 0x47])),
                    ]
                ),
            ]
        ))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .image)
        XCTAssertEqual(entry.displayText, "Image")
        XCTAssertTrue(entry.matches(contentFilter: .image))
        XCTAssertTrue(entry.matches(searchText: "remote-image.png"))
        XCTAssertNotNil(entry.items.first?.imageBlobID)
    }

    func testRemoteImageFileURLWithoutImageRepresentationIsClassifiedAsImage() throws {
        let imageData = try XCTUnwrap(Data(base64Encoded: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII="))
        let imageFileURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
            .appendingPathComponent("pulse-remote-image-\(UUID().uuidString).png")
        try imageData.write(to: imageFileURL)
        defer { try? FileManager.default.removeItem(at: imageFileURL) }

        let store = makeStore()
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 5,
            capturedAt: Date(),
            declaredSource: ClipboardApplicationSource(
                name: "WeChat",
                bundleIdentifier: "com.tencent.xinWeChat",
                bundlePath: nil,
                rawValue: nil
            ),
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [ClipboardKnownMarker.remoteClipboard.rawValue],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.file-url", data: Data(imageFileURL.absoluteString.utf8)),
                    ]
                ),
            ]
        ))

        let entry = try XCTUnwrap(store.entries.first)
        let item = try XCTUnwrap(entry.items.first)
        let imageBlobID = try XCTUnwrap(item.imageBlobID)

        XCTAssertEqual(entry.kind, .image)
        XCTAssertEqual(entry.displayText, "Image")
        XCTAssertTrue(entry.matches(contentFilter: .image))
        XCTAssertFalse(entry.matches(contentFilter: .file))
        XCTAssertTrue(entry.matches(searchText: imageFileURL.lastPathComponent))
        XCTAssertEqual(item.representations.last?.type, "public.png")
        XCTAssertEqual(store.imageData(for: imageBlobID), imageData)
    }

    func testLoadedHistoryRepairsRemoteImageFileEntries() throws {
        let rootURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
            .appendingPathComponent("PulseClipboardStoreTests-\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: rootURL) }

        let imagePath = "/Users/example/Library/Group Containers/group.com.apple.coreservices.useractivityd/old-remote.png"
        let persistence = ClipboardHistoryPersistence(rootURL: rootURL)
        try persistence.save(entries: [
            ClipboardHistoryEntry(
                id: UUID(),
                changeCount: 6,
                createdAt: Date(),
                kind: .file,
                displayText: imagePath,
                searchableText: imagePath,
                markerTypes: [ClipboardKnownMarker.remoteClipboard.rawValue],
                declaredSource: nil,
                inferredSource: nil,
                items: [
                    ClipboardHistoryItem(
                        id: UUID(),
                        kind: .file,
                        displayText: imagePath,
                        searchableText: imagePath,
                        markerTypes: [ClipboardKnownMarker.remoteClipboard.rawValue],
                        representations: [],
                        imageBlobID: nil,
                        imagePixelWidth: nil,
                        imagePixelHeight: nil
                    ),
                ],
                fingerprint: "stored-remote-image-file"
            ),
        ])

        let store = ClipboardHistoryStore(
            userDefaults: UserDefaults(suiteName: "PulseClipboardStoreTests-\(UUID().uuidString)") ?? .standard,
            client: FakeClipboardPasteboardClient(),
            persistence: persistence,
            pasteCommandPoster: FakeClipboardFocusedPasteCommandPoster()
        )

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .image)
        XCTAssertEqual(entry.displayText, "Image")
        XCTAssertTrue(entry.matches(contentFilter: .image))
        XCTAssertFalse(entry.matches(contentFilter: .file))
        XCTAssertTrue(entry.matches(searchText: "old-remote.png"))
    }

    func testFileURLProvidedAsURLTypeParsesAsFile() throws {
        let store = makeStore()
        let fileURL = URL(fileURLWithPath: "/tmp/pulse-export.zip")
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 5,
            capturedAt: Date(),
            declaredSource: nil,
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.url", data: Data(fileURL.absoluteString.utf8)),
                    ]
                ),
            ]
        ))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .file)
        XCTAssertEqual(entry.displayText, fileURL.path)
        XCTAssertTrue(entry.matches(contentFilter: .file))
        XCTAssertFalse(entry.matches(contentFilter: .url))
    }

    func testStandalonePlainTextHTTPURLParsesAsURL() throws {
        let store = makeStore()
        let url = "https://search.jd.com/Search?keyword=usb%2Btype-c%205%E7%B1%B3&enc=utf-8&pvid=0c7d7adfcbc9485c8bb53fa5b8d52ff7"

        store.record(textSnapshot(changeCount: 6, text: "  \(url)\n"))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .url)
        XCTAssertEqual(entry.displayText, url)
        XCTAssertTrue(entry.matches(contentFilter: .url))
        XCTAssertFalse(entry.matches(contentFilter: .text))
    }

    func testStandalonePlainTextEmailParsesAsURL() throws {
        let store = makeStore()

        store.record(textSnapshot(changeCount: 6, text: "person@example.com"))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .url)
        XCTAssertEqual(entry.displayText, "person@example.com")
        XCTAssertTrue(entry.matches(contentFilter: .url))
        XCTAssertFalse(entry.matches(contentFilter: .text))
    }

    func testPlainTextContainingURLRemainsText() throws {
        let store = makeStore()

        store.record(textSnapshot(changeCount: 6, text: "Open https://example.com and review notes."))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .text)
        XCTAssertTrue(entry.matches(contentFilter: .text))
        XCTAssertFalse(entry.matches(contentFilter: .url))
    }

    func testMultiplePlainTextURLsRemainText() throws {
        let store = makeStore()

        store.record(textSnapshot(changeCount: 6, text: "https://example.com\nhttps://example.org"))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .text)
        XCTAssertTrue(entry.matches(contentFilter: .text))
        XCTAssertFalse(entry.matches(contentFilter: .url))
    }

    func testStandalonePlainTextFileURLParsesAsFile() throws {
        let store = makeStore()
        let fileURL = URL(fileURLWithPath: "/tmp/pulse-export.zip")

        store.record(textSnapshot(changeCount: 6, text: fileURL.absoluteString))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .file)
        XCTAssertEqual(entry.displayText, fileURL.path)
        XCTAssertTrue(entry.matches(contentFilter: .file))
        XCTAssertFalse(entry.matches(contentFilter: .url))
    }

    func testLoadedLegacyPlainTextURLIsRepairedAsURL() throws {
        let rootURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
            .appendingPathComponent("PulseClipboardStoreTests-\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: rootURL) }

        let persistence = ClipboardHistoryPersistence(rootURL: rootURL)
        let store = ClipboardHistoryStore(
            userDefaults: UserDefaults(suiteName: "PulseClipboardStoreTests-\(UUID().uuidString)") ?? .standard,
            client: FakeClipboardPasteboardClient(),
            persistence: persistence,
            pasteCommandPoster: FakeClipboardFocusedPasteCommandPoster()
        )
        let url = "https://github.com/dorrrway/pulse"
        store.record(textSnapshot(changeCount: 1, text: url))
        var legacyEntry = try XCTUnwrap(store.entries.first)
        legacyEntry.kind = .text
        legacyEntry.items[0].kind = .text
        try persistence.save(entries: [legacyEntry])

        let restoredStore = ClipboardHistoryStore(
            userDefaults: UserDefaults(suiteName: "PulseClipboardStoreTests-\(UUID().uuidString)") ?? .standard,
            client: FakeClipboardPasteboardClient(),
            persistence: persistence,
            pasteCommandPoster: FakeClipboardFocusedPasteCommandPoster()
        )

        let entry = try XCTUnwrap(restoredStore.entries.first)
        XCTAssertEqual(entry.kind, .url)
        XCTAssertEqual(entry.items.first?.kind, .url)
        XCTAssertEqual(entry.displayText, url)
    }

    func testRemoteClipboardDoesNotUseLocalInferredSource() throws {
        let store = makeStore()
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 6,
            capturedAt: Date(),
            declaredSource: nil,
            inferredSource: ClipboardApplicationSource(
                name: "WeChat",
                bundleIdentifier: "com.tencent.xinWeChat",
                bundlePath: "/Applications/WeChat.app",
                rawValue: nil
            ),
            items: [
                ClipboardCapturedItem(
                    markerTypes: [ClipboardKnownMarker.remoteClipboard.rawValue],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.utf8-plain-text", data: Data("remote text".utf8)),
                    ]
                ),
            ]
        ))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertNil(entry.inferredSource)
        XCTAssertNil(entry.primarySource)
        XCTAssertFalse(entry.matches(searchText: "WeChat"))
        XCTAssertTrue(entry.matches(searchText: ClipboardKnownMarker.remoteClipboard.rawValue))
    }

    func testLoadedHistoryRestoresWeChatSourceFromStoredPasteboardTypes() throws {
        let rootURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
            .appendingPathComponent("PulseClipboardStoreTests-\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: rootURL) }

        let persistence = ClipboardHistoryPersistence(rootURL: rootURL)
        try persistence.save(entries: [
            ClipboardHistoryEntry(
                id: UUID(),
                changeCount: 7,
                createdAt: Date(),
                kind: .image,
                displayText: "Image",
                searchableText: "Image",
                markerTypes: [ClipboardKnownMarker.remoteClipboard.rawValue],
                declaredSource: nil,
                inferredSource: nil,
                items: [
                    ClipboardHistoryItem(
                        id: UUID(),
                        kind: .image,
                        displayText: "Image",
                        searchableText: "Image",
                        markerTypes: [ClipboardKnownMarker.remoteClipboard.rawValue],
                        representations: [
                            ClipboardStoredRepresentation(
                                type: "com.trolltech.anymime.WeChatScreenshotFormat",
                                blobID: "wechat-marker",
                                byteCount: 1
                            ),
                        ],
                        imageBlobID: nil,
                        imagePixelWidth: nil,
                        imagePixelHeight: nil
                    ),
                ],
                fingerprint: "remote-wechat-image"
            ),
        ])

        let store = ClipboardHistoryStore(
            userDefaults: UserDefaults(suiteName: "PulseClipboardStoreTests-\(UUID().uuidString)") ?? .standard,
            client: FakeClipboardPasteboardClient(),
            persistence: persistence,
            pasteCommandPoster: FakeClipboardFocusedPasteCommandPoster()
        )

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.declaredSource?.bundleIdentifier, "com.tencent.xinWeChat")
        XCTAssertTrue(entry.matches(searchText: "com.tencent.xinWeChat"))
    }

    func testContentFiltersMatchEntryItems() {
        let store = makeStore()
        let fileURL = URL(fileURLWithPath: "/tmp/pulse-report.pdf")
        store.record(textSnapshot(changeCount: 1, text: "plain text"))
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 2,
            capturedAt: Date(),
            declaredSource: nil,
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.url", data: Data("https://example.com".utf8)),
                    ]
                ),
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.file-url", data: Data(fileURL.absoluteString.utf8)),
                    ]
                ),
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "public.png", data: Data([0x89, 0x50, 0x4E, 0x47])),
                    ]
                ),
            ]
        ))

        store.selectedContentFilter = .all
        XCTAssertEqual(store.filteredEntries.count, 2)

        store.selectedContentFilter = .text
        XCTAssertEqual(store.filteredEntries.map(\.displayText), ["plain text"])

        store.selectedContentFilter = .url
        XCTAssertEqual(store.filteredEntries.map(\.changeCount), [2])

        store.selectedContentFilter = .file
        XCTAssertEqual(store.filteredEntries.map(\.changeCount), [2])

        store.selectedContentFilter = .image
        XCTAssertEqual(store.filteredEntries.map(\.changeCount), [2])

        store.searchText = "example.com"
        XCTAssertEqual(store.filteredEntries.map(\.changeCount), [2])
    }

    func testSearchIndexesTextualRepresentationsFromRichLinkPayloads() {
        let store = makeStore()
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 1,
            capturedAt: Date(),
            declaredSource: nil,
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(
                            type: "public.url",
                            data: Data("https://example.com/pulse-notes".utf8)
                        ),
                        ClipboardCapturedRepresentation(
                            type: "public.html",
                            data: Data("<a href=\"https://example.com/pulse-notes\">Quarterly Pulse Notes</a>".utf8)
                        ),
                    ]
                ),
            ]
        ))

        store.searchText = "Quarterly Pulse"
        XCTAssertEqual(store.filteredEntries.map(\.changeCount), [1])

        store.searchText = "pulse-notes"
        XCTAssertEqual(store.filteredEntries.map(\.changeCount), [1])
    }

    func testLegacyFilenamePasteboardTypeParsesAsFileWithoutImagePreview() throws {
        let store = makeStore()
        let paths = ["/tmp/pulse-report.pdf", "/tmp/pulse-notes.txt"]
        let data = try PropertyListSerialization.data(
            fromPropertyList: paths,
            format: .xml,
            options: 0
        )

        store.record(ClipboardPasteboardSnapshot(
            changeCount: 1,
            capturedAt: Date(),
            declaredSource: nil,
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(type: "NSFilenamesPboardType", data: data),
                    ]
                ),
            ]
        ))

        let entry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(entry.kind, .file)
        XCTAssertTrue(entry.displayText.contains("/tmp/pulse-report.pdf"))
        XCTAssertTrue(entry.matches(searchText: "pulse-notes.txt"))
        XCTAssertNil(entry.items.first?.imageBlobID)
    }

    func testCopyingStoredEntryDoesNotAddSelfGeneratedHistoryEntry() throws {
        let client = FakeClipboardPasteboardClient()
        client.changeCount = 2
        let store = makeStore(client: client)
        store.record(textSnapshot(changeCount: 1, text: "first"))
        store.record(textSnapshot(changeCount: 2, text: "second"))
        let olderEntry = try XCTUnwrap(store.entries.last)

        store.copy(olderEntry)
        store.record(textSnapshot(changeCount: client.changeCount, text: "first"))

        XCTAssertEqual(store.entries.map(\.displayText), ["second", "first"])
        XCTAssertEqual(store.lastCopiedEntryID, olderEntry.id)
    }

    func testPastingStoredEntryCopiesEntryAndPostsPasteCommand() throws {
        let client = FakeClipboardPasteboardClient()
        let pasteCommandPoster = FakeClipboardFocusedPasteCommandPoster()
        let store = makeStore(client: client, pasteCommandPoster: pasteCommandPoster)
        store.record(textSnapshot(changeCount: 1, text: "focused text"))
        let entry = try XCTUnwrap(store.entries.first)

        store.pasteIntoFocusedTarget(entry)

        XCTAssertEqual(pasteCommandPoster.postPasteCommandCallCount, 1)
        XCTAssertEqual(store.lastCopiedEntryID, entry.id)
        XCTAssertNil(store.accessIssue)
        XCTAssertTrue(client.writtenRepresentations.contains { representation in
            representation.type == "public.utf8-plain-text"
                && String(data: representation.data, encoding: .utf8) == "focused text"
        })
    }

    func testPastingStoredEntryReportsAccessibilityPermissionIssue() throws {
        let pasteCommandPoster = FakeClipboardFocusedPasteCommandPoster()
        pasteCommandPoster.result = .accessibilityPermissionRequired
        let store = makeStore(pasteCommandPoster: pasteCommandPoster)
        store.record(textSnapshot(changeCount: 1, text: "needs permission"))
        let entry = try XCTUnwrap(store.entries.first)

        store.pasteIntoFocusedTarget(entry)

        XCTAssertEqual(pasteCommandPoster.postPasteCommandCallCount, 1)
        XCTAssertEqual(store.lastCopiedEntryID, entry.id)
        XCTAssertEqual(store.accessIssue, .pasteCommandDenied)
    }

    func testDuplicateExternalPayloadMovesExistingEntryToTopWithoutDuplicating() throws {
        let store = makeStore()
        store.record(textSnapshot(changeCount: 1, text: "first"))
        store.record(textSnapshot(changeCount: 2, text: "second"))
        let originalFirstEntryID = try XCTUnwrap(store.entries.last?.id)

        store.record(textSnapshot(changeCount: 3, text: "first"))

        XCTAssertEqual(store.entries.count, 2)
        XCTAssertEqual(store.entries.first?.id, originalFirstEntryID)
        XCTAssertEqual(store.entries.first?.displayText, "first")
        XCTAssertEqual(store.entries.first?.changeCount, 3)
        XCTAssertEqual(store.entries.last?.displayText, "second")
    }

    func testDuplicatePlainTextURLRefreshesLegacyTextClassification() throws {
        let store = makeStore()
        let url = "https://github.com/dorrrway/pulse"
        store.record(textSnapshot(changeCount: 1, text: url))
        var legacyEntry = try XCTUnwrap(store.entries.first)
        legacyEntry.kind = .text
        legacyEntry.items[0].kind = .text
        store.entries[0] = legacyEntry
        let originalID = legacyEntry.id

        store.record(textSnapshot(changeCount: 2, text: url))

        let refreshedEntry = try XCTUnwrap(store.entries.first)
        XCTAssertEqual(store.entries.count, 1)
        XCTAssertEqual(refreshedEntry.id, originalID)
        XCTAssertEqual(refreshedEntry.changeCount, 2)
        XCTAssertEqual(refreshedEntry.kind, .url)
        XCTAssertEqual(refreshedEntry.items.first?.kind, .url)
    }

    func testSearchIncludesMarkerBackedConcealedText() {
        let store = makeStore()
        store.record(ClipboardPasteboardSnapshot(
            changeCount: 1,
            capturedAt: Date(),
            declaredSource: nil,
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [ClipboardKnownMarker.transient.rawValue],
                    representations: [
                        ClipboardCapturedRepresentation(type: ClipboardKnownMarker.transient.rawValue, data: Data()),
                        ClipboardCapturedRepresentation(type: "public.utf8-plain-text", data: Data("one time code".utf8)),
                    ]
                ),
            ]
        ))

        store.searchText = "code"

        XCTAssertEqual(store.filteredEntries.count, 1)
        XCTAssertEqual(store.filteredEntries.first?.shouldMaskByDefault, true)
    }

    private func makeStore(
        client: FakeClipboardPasteboardClient = FakeClipboardPasteboardClient(),
        pasteCommandPoster: FakeClipboardFocusedPasteCommandPoster = FakeClipboardFocusedPasteCommandPoster()
    ) -> ClipboardHistoryStore {
        let rootURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
            .appendingPathComponent("PulseClipboardStoreTests-\(UUID().uuidString)", isDirectory: true)
        return ClipboardHistoryStore(
            userDefaults: UserDefaults(suiteName: "PulseClipboardStoreTests-\(UUID().uuidString)") ?? .standard,
            client: client,
            persistence: ClipboardHistoryPersistence(rootURL: rootURL),
            pasteCommandPoster: pasteCommandPoster
        )
    }

    private func textSnapshot(
        changeCount: Int,
        text: String,
        capturedAt: Date? = nil
    ) -> ClipboardPasteboardSnapshot {
        ClipboardPasteboardSnapshot(
            changeCount: changeCount,
            capturedAt: capturedAt ?? Date().addingTimeInterval(TimeInterval(changeCount)),
            declaredSource: nil,
            inferredSource: nil,
            items: [
                ClipboardCapturedItem(
                    markerTypes: [],
                    representations: [
                        ClipboardCapturedRepresentation(
                            type: "public.utf8-plain-text",
                            data: Data(text.utf8)
                        ),
                    ]
                ),
            ]
        )
    }
}

@MainActor
private final class FakeClipboardFocusedPasteCommandPoster: ClipboardFocusedPasteCommandPosting {
    var result: ClipboardFocusedPasteCommandResult = .posted
    var postPasteCommandCallCount = 0

    func postPasteCommand() -> ClipboardFocusedPasteCommandResult {
        postPasteCommandCallCount += 1
        return result
    }
}

@MainActor
private final class FakeClipboardPasteboardClient: ClipboardPasteboardClient {
    struct WrittenRepresentation: Equatable {
        var type: String
        var data: Data
    }

    var changeCount = 0
    var accessBehavior: ClipboardPasteboardAccessBehavior = .alwaysAllow
    var snapshot = ClipboardPasteboardSnapshot(
        changeCount: 0,
        capturedAt: Date(timeIntervalSince1970: 0),
        declaredSource: nil,
        inferredSource: nil,
        items: []
    )
    var writtenRepresentations: [WrittenRepresentation] = []

    func readSnapshot(capturedAt: Date, inferredSource: ClipboardApplicationSource?) throws -> ClipboardPasteboardSnapshot {
        snapshot
    }

    func write(entry: ClipboardHistoryEntry, blobData: [String: Data]) throws {
        changeCount += 1
        writtenRepresentations = entry.items.flatMap { item in
            item.representations.compactMap { representation in
                guard let data = blobData[representation.blobID] else {
                    return nil
                }

                return WrittenRepresentation(type: representation.type, data: data)
            }
        }
    }
}
